### ISSUE TITLE
Segfault after upgrading to commit 2016-01-14

### ISSUE THREAD

**Issue by ibcs01** [karlheyes/icecast-kh#129]
After upgrading from commit 2015-12-30 to 2016-01-14, Icecast crashes every time we play audio and stop it from an HTML5 audio player. 
I would guess this has something to do with the url auth method we use.

Icecast crashes with the following error:
[138542.261233] icecast[16137]: segfault at 50 ip 00000000004210eb sp 00007f146f33abe0 error 4 in icecast[400000+5e000]

Icecast was built in debuge mode using make debug.
You can find the core dump and binary here: http://tiny.cc/wrk67x

The files you need are:
- core-2016-01-14 ( Core dump )
- icecast-2016-01-14 ( Binary )

Would be nice if someone could check out what causes this.
Thanks!

Grt Sven

**Comment by karlheyes** [comment]
looks like you have plenty of mounts defined for use in that. Which html player are you using to trigger this problem, just so I can try to reproduce it. 

karl.

**Comment by ibcs01** [comment]
Hi Karl,

We use Soundmanager2 to play the audio stream.
It works fine until we upgrade to the latest commit.

If you need more details, please let me know.

Grt Sven

**Comment by karlheyes** [comment]
I did have a try with that but haven't caused a crash yet.  It may be a particular combination of things that you are seeing which I haven't quite matched yet, but while investigating this though, I did see a possible race case when dealing with error responses because of the recent commits, it's actually the same code path that a normal listener exit would take if auth is used .  That issue is now fixed in the master branch.

karl.

**Comment by edinsof** [comment]
Hi karl mi icecast same is crash after upgrading to commit 2016-01-14 #129

I'm using centovacast and stream crash show this error.

[2016-01-16  20:16:40] EROR connection/wait_for_serversock signalfd descriptor became invalid, doing thread restart

**Comment by karlheyes** [comment]
If you are getting a core from 6c2518d9e then let me know the specifics, that message is not related AFAICT.  Maybe a ssh to a test icecast showing the issue would be the best approach.

karl.

**Comment by ibcs01** [comment]
Hi Karl,

Thanks for your support.

Unfortunately, the problem still persists. 
This is what happens:

- When playing the OGG stream in Winamp, you can start and stop and start the stream again as many times you like without problems.
- When you start the mp3 stream in Winamp, and click start and stop repeatedly, Icecast crashes after a few attempts. This is constant and always happens when i try this.

For each OGG mountpoint, we have defined an mp3 mount to.
Users broadcast only OGG and we transcode it to mp3 at the moment a listeners connects.
The problem occurs when listening to this transcoded mp3 stream.
The problem does not persist if we downgrade to the commit of 30-12-2015.

We have about 75 mountpoints defined in our icecast.xml file and they are all defined in the following fashion:

  <mount>
    <mount-name>/STREAMNAME.ogg</mount-name>
    <password>hackme</password>
    <admin_comments_only>0</admin_comments_only>
    <dump-file>/data/icecast/1/dumpfiles/dump.ogg</dump-file>
    <authentication type="url">
      <option name="allow_duplicate_users" value="0"/>
      <option name="realm" value="Livesets"/>
      <option name="mount_add" value="https://website.com/mount/add/2"/>
      <option name="mount_remove" value="https://website.com/mount/remove/2"/>
      <option name="listener_add" value="https://website.com/listener/add/2"/>
      <option name="listener_remove" value="https://website.com/listener/remove/2"/>
    </authentication>
  </mount>
  <mount>
    <mount-name>/STREAMNAME.mp3</mount-name>
    <password>hackme</password>
    <fallback-mount>/fallback/STREAMNAME.mp3</fallback-mount>
    <fallback-override>1</fallback-override>
    <limit-rate>128k</limit-rate>
    <mp3-metadata-interval>4096</mp3-metadata-interval>
    <authentication type="url">
      <option name="allow_duplicate_users" value="0"/>
      <option name="realm" value="Website"/>
      <option name="listener_add" value="https://website.com/listener/add/2"/>
      <option name="listener_remove" value="https://website.com/listener/remove/2"/>
    </authentication>
  </mount>

Would be great if you could have a closer look, when you find the time.

You can find the core dump and binary here: http://tiny.cc/wrk67x

The files you need are:
- core-2016-01-17 ( Core dump )
- icecast-2016-01-17 ( Binary )

Grt Sven

**Comment by karlheyes** [comment]
I saw some of the details, except the logging information, took my a while to find the mount section details.  The trigger case for the crash is a listing of listeners, which is finding an old client which is no longer valid.  What I don't know is when that listing occurs in relation to the listener exiting, as these are two separate events.

karl.

**Comment by ibcs01** [comment]
The counting of listeners occurs in the listener_remove trigger. What it does is fetch the admin/index.xml file from the Icecast server with curl and get the listener count for the specific mount.
Problem causes only problems when firing the listener_remove trigger on an mp3 mount.

Please let me know if you need more data.

Grt Sven

**Comment by karlheyes** [comment]
found something that would have an effect you are seeing, a combination of the fallback override, and listener remove trigger being present with the recent auth commits.  A setting being zero'd when it should not. fix now pushed.

karl.

**Comment by ibcs01** [comment]
Hi Karl,

Installed it today and Icecast runs fine again.
Thanks for your support!

Best regards, 
Sven
